// Midnight Ticket Stub: hero-led discovery with one direct watch path and horizontal catalog rails.
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowRight, ChevronRight, Film, Search, ShieldCheck, Sparkles } from "lucide-react";
import { TitleCard } from "@/components/TitleCard";
import { films, genres } from "@/lib/catalog";

export default function Home() {
  const [query, setQuery] = useState("");
  const [genre, setGenre] = useState("All");
  const [saved, setSaved] = useState<string[]>(() => JSON.parse(window.localStorage.getItem("stream-wallet") ?? "[]"));
  const toggleSave = (id: string) => setSaved((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; window.localStorage.setItem("stream-wallet", JSON.stringify(next)); return next; });
  const filtered = useMemo(() => films.filter((film) => `${film.title} ${film.genre} ${film.language}`.toLowerCase().includes(query.toLowerCase()) && (genre === "All" || film.genre.includes(genre))), [query, genre]);
  const savedFilms = films.filter((film) => saved.includes(film.id));

  return <div className="page-wrap">
    <header className="topbar"><div className="topbar__context"><span className="live-dot" /> Open-film catalog <span className="topbar__divider">/</span> <span>Provider handoffs</span></div><div className="topbar__tools"><button className="topbar__search-trigger" onClick={() => document.getElementById("catalog-search")?.focus()}><Search size={15} /> Search titles <kbd>/</kbd></button><span className="topbar__status"><ShieldCheck size={15} /> source-aware</span></div></header>
    <section className="hero-panel"><img className="hero-panel__image" src="https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=2200&q=88" alt="Warm projector light in a cinema" /><div className="hero-panel__wash" /><div className="hero-panel__copy"><p className="eyebrow eyebrow--light">A clearer way to choose</p><h1>Pick a title.<br /><em>Keep the night moving.</em></h1><p className="hero-panel__intro">A focused watchlist for open films and authorized provider links. No clutter, no movie library hiding behind the button.</p><Link className="button button--primary" href="/title/cosmos-laundromat">Watch the featured film <ArrowRight size={17} /></Link></div><div className="hero-panel__note"><span>01</span><p>Featured from the<br /><strong>open film shelf</strong></p></div></section>
    <section className="quick-stats"><div><strong>04</strong><span>open films</span></div><div><strong>HD</strong><span>where available</span></div><div><strong>09+</strong><span>caption tracks</span></div><div><strong>01</strong><span>clear watch path</span></div></section>
    <section className="content-section" id="explore"><div className="section-heading"><div><div className="section-kicker"><span>PROGRAM 01</span><i /></div><p className="eyebrow">Find your next screen</p><h2>Explore the shelf</h2></div><div className="section-heading__aside"><span>Original metadata · external playback</span><ChevronRight size={18} /></div></div><div className="search-row"><div className="search-field"><Search size={18} /><input id="catalog-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by title, genre, or language" /></div><div className="genre-tabs" aria-label="Filter by genre">{genres.map((item) => <button key={item} className={genre === item ? "genre-tab is-active" : "genre-tab"} onClick={() => setGenre(item)}>{item}</button>)}</div></div><div className="rail-heading"><h3>{query || genre !== "All" ? "Search results" : "The open-film shelf"}</h3><span>{filtered.length} titles · swipe to browse</span></div>{filtered.length ? <div className="title-grid">{filtered.map((film) => <TitleCard key={film.id} film={film} saved={saved.includes(film.id)} onToggleSave={toggleSave} />)}</div> : <div className="empty-state"><Film size={25} /><h3>No titles match that search.</h3><p>Try another phrase or return to the full shelf.</p></div>}</section>
    <section className="content-section content-section--split" id="wallet"><div className="wallet-callout"><div className="wallet-callout__icon"><Sparkles size={20} /></div><div><p className="eyebrow">Your small queue</p><h2>Keep the good ones close.</h2><p>Save a title to your wallet. It stays in this browser for now—no account required.</p></div><Link href="/#explore" className="button button--quiet">Browse shelf <ArrowRight size={16} /></Link></div><div className="wallet-list">{savedFilms.length ? savedFilms.slice(0, 2).map((film) => <TitleCard key={film.id} film={film} saved onToggleSave={toggleSave} compact />) : <div className="wallet-empty"><span className="ticket-line" /><p>Your wallet is empty.</p><span>Tap the bookmark on a title to save it here.</span></div>}</div></section>
    <footer className="site-footer"><div className="footer-brand"><Film size={17} /><span>Stream-Wallet</span></div><p>Prototype catalog using open-film demo links. Replace provider records with documented rights before launch.</p><span className="footer-mark">© 2026</span></footer>
  </div>;
}
